#!/bin/bash
e="echo -e "
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
Version="./pockat/Version"
update="./pockat/info"
HO="/data/data/com.termux/files/usr/lib/$versiENC"
musik="bash $HOME/ENC/MODULE.sh"
letakgalirus_hozoo="/data/data/com.termux/files/usr/etc/apt"
internalsc="/data/data/com.termux/files/usr/include/jso"
termux_id=$(whoami)
# Color codes
m="\033[1;31m"   # Merah
h="\033[1;32m"   # Hijau
k="\033[1;33m"   # Kuning
b="\033[1;34m"   # Biru
bl="\033[1;36m"  # Biru Muda
p="\033[1;37m"   # Putih
u="\033[1;35m"   # Ungu
pu="\033[1;30m"  # Abu-abu
c="\033[1;96m"   # Cyan Terang
bg_m="\033[41m"  # Latar Belakang Merah
bg_h="\033[42m"  # Latar Belakang Hijau
bg_k="\033[43m"  # Latar Belakang Kuning
bg_b="\033[44m"  # Latar Belakang Biru
bg_bl="\033[46m" # Latar Belakang Biru Muda
bg_p="\033[47m"  # Latar Belakang Putih
bg_u="\033[45m"  # Latar Belakang Ungu
bg_pu="\033[40m" # Latar Belakang Abu-abu
res="\033[0m"    # Reset semua atribut


# Warna
m="\033[1;31m"   # Merah
h="\033[1;32m"   # Hijau
k="\033[1;33m"   # Kuning
b="\033[1;34m"   # Biru
bl="\033[1;36m"  # Biru Muda
p="\033[1;37m"   # Putih
u="\033[1;35m"   # Ungu
pu="\033[1;30m"  # Abu-abu
c="\033[1;96m"   # Cyan Terang


$e $u"   ⣀⢀⣠⣤⠴⠶⠚⠛⠉⣹⡇ ⢸     ⢰⣄    ⠈⢦⢰     ⠈⢳⡀⠈⢧    ⢸    "
 $e $u" ⠉   ⡏ ⢰⠃   ⣿⡇ ⢸⡀    ⢸⣸⡆   ⠰⣌⣧⡆ ⢷⡀  ⣄⢳  ⢣   ⢸    "
 $e $u"     ⡇ ⠘   ⢀⣿⣇ ⠸⡇⣆    ⣿⣿⡀   ⢹⣾⡇ ⢸⢣  ⠘⣿⣇ ⠈⢧  ⠘ ⢠   "
 $e $u"    ⢀⡇ ⡀   ⢸⠈⢻⡄ ⢷⣿    ⢹⡏⣇ ⣀⣀ ⣿⣧ ⢸⠾⣇⣠⣄⣸⣿⡄ ⠘⡆    ⠆    "
 $e $u"    ⣾⢿ ⠇   ⢸  ⢳⡀⢸⣿⡆   ⣬⣿⡿⠟⠋⠉⠙⠻⣽⣀⡏ ⠙⠃⢹⡙⡿⣷  ⢹    ⠰⠒ "
 $e $u"   ⢸⣿⣿⣇⢸   ⢸⣦⣤⡀⣷⣸⡟⢧⣀⡴⠶⠿⠻⡄⣀⣤⣴⡾⠖⠚⠿⡀   ⠈⣧⠁⠹⠆  ⣇     "
 $e $u"  ⢀⢸⣀⣼⣿⣼⡆ ⢀⡘⡇  ⠹⡟⢷⡜⢉⣠⣠⣠⣀⣤⡿⣛⣥⣶⣾⡿⠛⠿⠿⣶⣦⡤⢹ ⢀   ⢹⡄    "
 $e $u"  ⢸⢸⡛⠁ ⠙⢿⠋⠉⠉⠻   ⢿⣄⠈⠁   ⢉⢟⣴⡿⠿$b⠟⢁⠇ $u   ⠹⣿⠻⡇⢸   ⠈⣷   "
 $e $u"⣀⣀⣘⣿⡇ ⢀⣠⣤⣶⣶⣶⣾⣦⡀ ⠈⡿      ⣿$b⠟⠳⠦⡤⠊    $u ⣸⠇ ⡇⣼ ⢰  ⢹⣇ "
 $e $u"⠛⠁⠈⣿⣷⣧⣴⣿⠿⠛⣿⠿⣿⣿⡿⠗         ⠁  ⣠⣴⣶⠿⠿⠿⡷⢛⠕⠷⡄⣧⣿ ⢸  ⠸⣿⡄  "
 $e $u" ⢠⣿⢿⣿⣿⠁ $b ⠈⠳⠤⠶⠃ $u ⢰⡀       ⣠⣿⣿⠟⣱⠒⡠⢆⡴⣣⣯⢞⣴⡟⢿⡄⡏   ⡏⢷⡀ "
 $e $u" ⡌⣿ ⠙⣿⡦⢀⣤⡴⣶⠖⣲⠆⢀⠞⠁⠱     ⠠⣾⠟⠛⡡⠞⠁⢀⡴⢋⢎⣽⡿⣫⠋ ⠘⢷⠃⡄  ⡇⠈⣿⡀   "
 $e $u" ⣇⢹⣦ ⠼⢃⡾⢋⣶⢃⡼⣹⡳⠃⠊        ⠁   ⠈⠠⠋ ⡰⠋ ⢘⣇⡇ ⢠⠟ ⡇    ⢹⡵  "
 $e $u" ⢻⣌⢿⡆ ⡝⣼⠟⣩⢏⣾⠟⠁                ⢀⠞    ⠈ ⣠⠏⣠⣾⡇    ⠘⣷  "
 $e $u" ⢸⣿⣿⣷⠆⢠⠏⡴⠃⡡⠋      ⣀⣠⠤⠔⠒⠤⣄⣀  ⢀⣰⠏    ⢀⣠⡾⠗⠋⢰⠏⡇  ⠘ ⠰⢻   "
 $e $u"⣇ ⠘⣿⣿⣟⠻⣄⡞ ⠐⠁     ⣠⠞⣩⣤⣶⣶⣾⣷⣶⣬⣿⣿⣿⡏    ⠉⠉⠁   ⢸⡆⡇         "
 $e $u"⠹⡄ ⠹⣿⣿⡄ ⠉⠉ ⡀  ⠈⢻⣾⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿           ⣼⣇⣧        "
 $e $u"⣿⢦⣀⠘⢿⣷⡀  ⡀⢦    ⠹⣿⣿⠏⠙⢻⣿⡿⠛⠉ ⠸⣿⠃         ⢀⣴⣿⣿⣿  ⡆  ⡀         "
 $e $u"⢼⣿ ⠈⢳⣤⣉⣻⣤⣀⣉⣩⠆    ⠹⡿  ⠈⡿    ⣸⡇      ⠓⠂ ⣠⣾⣿⣿⡿⢿⡄ ⣧  ⠹    "
 $e $u"⣾⠃ ⣠⣿⣿⣿⣿⣿⣿⣄       ⡇  ⢸⡇  ⢠⠴⣿⡄       ⣠⣾⣿⣿⣿⡿⣧⣀⠧⣰⣻⢄       "
 $e $u"⠛⠶⢾⣿⣽⣭⣽⣭⢹⣷ ⢹⣦⣀    ⡄  ⣸⡀  ⠁⣰⣧⣽    ⢀⣴⣾⣿⣿⡟⣻⣿⣿⣿⣿⢠⣿⣧⡸⣷⣄      "
 $e $u"  ⠈⠙⠿⣿⣿⣿⠏ ⣾⣿⣿⣷⣦⣀ ⢇  ⠈⠁ ⣠⠔⠁    ⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠏⣼⣿⠏⣷⡈⠉        "
 $e $u"      ⠙⠻⣶⣾⣿⣿⣿⣿⣿⣿⣷⣾⡆   ⡾⠁   ⣀⡴⠞⠛⣛⣿⡿⠿⠛⠛⠉⠉   ⢰⣿⡿⠂⠈⠻⡄     "
 $e $u"         ⠙⢎⠉⠛⠻⠿⠿⠿⠿⠿⣇⠠⠸⣇⣀⣤⣴⣾⡭⠶⠛⠋⠉          ⣾⣿⠇   ⠘      "
 $e $u"           ⠑⣤⡀     ⠈⣳ ⣿⠛⠻⠛⠉              ⣸⣿⡯       "
echo -e "$u╔═════════════════════════════════╗$u"
echo -e "$u║  $k•💃 KAMU UDAH MAKAN BELUM 💃   $u║$u"
echo -e "$u╚═════════════════════════════════╝$u"
echo -e "$u║ $k[01]$h. MENU YOUTUBE              $u║"
echo -e "$u║ $k[02]$h. MENU TIKTOK               $u║"
echo -e "$u║ $k[03]$h. MENU SNCAK VIDIO          $u║"
echo -e "$u║ $k[04]$h. MENU FACEBOOK             $u║"
echo -e "$u║ $k[05]$h. MENU IG                   $u║"
echo -e "$u║ $k[06]$h. LAPOR BUG                 $u║"
echo -e "$u║ $k[07]$h. UPDATE SC                 $u║"
echo -e "$u║ $k[08]$h. EXIT                      $u║"
echo -e "$u╚═════════════════════════════════╝$u"
echo -e "$u║"
echo -e "$u║"
echo -e "$u║"
read -p "╚═════(CY78㉿ROOT)═════>: " cy78

mpv MUSIK.mp3
if [ "$cy78" = 1 ] || [ "$cy78" = 01 ]; then
mpv /MUSIK.mp3
clear 
termux-setup-storage -y
clear
xdg-open "https://publer.io/tools/youtube-short-downloader"
fi
if [ "$cy78" = 2 ] || [ "$cy78" = 02 ]; then
mpv MUSIK.mp3
clear
termux-setup-storage -y
clear
xdg-open"https://snaptik.app/ID2"
fi
if [ "$cy78" = 3 ] || [ "$cy78" = 03 ]; then
mpv MUSIK.mp3
clear
termux-setup-storage -y
clear
xdg-open "https://getsnackvideo.com/"
fi
if [ "$cy78" = 4 ] || [ "$cy78" = 04 ]; then
clear
termux-setup-storage -y
clear
mpv MUSIK.mp3
xdg-open "https://snapsave.app/"
fi
if [ "$cy78" = 5 ] || [ "$cy78" = 05 ]; then
mpv MUSIK.mp3
clear
termux-setup-storage -y
clear
mpv MUSIK.mp3
xdg-open "https://snapinsta.app/"
fi
if [ "$cy78" = 6 ] || [ "$cy78" = 06 ]; then
mpv MUSIK.mp3
clear
termux-setup-storage -y
clear
xdg-open "https://wa.me/628999859595?text=Kak%20hozoocute%20ada%20bug%20sc%20tolong%20di%20update"
fi
if [ "$cy78" = 7 ] || [ "$cy78" = 07 ]; then
mpv MUSIK.mp3
clear
termux-setup-storage -y
clear
git clone https://github.com/Kingcy78/TOOLS9
cd TOOLS9
chmod +x 1
./1
fi
