#!/bin/bash
e="echo -e "
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
Version="./pockat/Version"
update="./pockat/info"
HO="/data/data/com.termux/files/usr/lib/$versiENC"
musik="bash $HOME/ENC/MODULE.sh"
letakgalirus_hozoo="/data/data/com.termux/files/usr/etc/apt"
internalsc="/data/data/com.termux/files/usr/include/jso"
termux_id=$(whoami)
# Color codes
m="\033[1;31m"   # Merah
h="\033[1;32m"   # Hijau
k="\033[1;33m"   # Kuning
b="\033[1;34m"   # Biru
bl="\033[1;36m"  # Biru Muda
p="\033[1;37m"   # Putih
u="\033[1;35m"   # Ungu
pu="\033[1;30m"  # Abu-abu
c="\033[1;96m"   # Cyan Terang
bg_m="\033[41m"  # Latar Belakang Merah
bg_h="\033[42m"  # Latar Belakang Hijau
bg_k="\033[43m"  # Latar Belakang Kuning
bg_b="\033[44m"  # Latar Belakang Biru
bg_bl="\033[46m" # Latar Belakang Biru Muda
bg_p="\033[47m"  # Latar Belakang Putih
bg_u="\033[45m"  # Latar Belakang Ungu
bg_pu="\033[40m" # Latar Belakang Abu-abu
res="\033[0m"    # Reset semua atribut


# Warna
m="\033[1;31m"   # Merah
h="\033[1;32m"   # Hijau
k="\033[1;33m"   # Kuning
b="\033[1;34m"   # Biru
bl="\033[1;36m"  # Biru Muda
p="\033[1;37m"   # Putih
u="\033[1;35m"   # Ungu
pu="\033[1;30m"  # Abu-abu
c="\033[1;96m"   # Cyan Terang

# Menu
clear
$e $u"   ⣀⢀⣠⣤⠴⠶⠚⠛⠉⣹⡇ ⢸     ⢰⣄    ⠈⢦⢰     ⠈⢳⡀⠈⢧    ⢸    "
 $e $u" ⠉   ⡏ ⢰⠃   ⣿⡇ ⢸⡀    ⢸⣸⡆   ⠰⣌⣧⡆ ⢷⡀  ⣄⢳  ⢣   ⢸    "
 $e $u"     ⡇ ⠘   ⢀⣿⣇ ⠸⡇⣆    ⣿⣿⡀   ⢹⣾⡇ ⢸⢣  ⠘⣿⣇ ⠈⢧  ⠘ ⢠   "
 $e $u"    ⢀⡇ ⡀   ⢸⠈⢻⡄ ⢷⣿    ⢹⡏⣇ ⣀⣀ ⣿⣧ ⢸⠾⣇⣠⣄⣸⣿⡄ ⠘⡆    ⠆    "
 $e $u"    ⣾⢿ ⠇   ⢸  ⢳⡀⢸⣿⡆   ⣬⣿⡿⠟⠋⠉⠙⠻⣽⣀⡏ ⠙⠃⢹⡙⡿⣷  ⢹    ⠰⠒ "
 $e $u"   ⢸⣿⣿⣇⢸   ⢸⣦⣤⡀⣷⣸⡟⢧⣀⡴⠶⠿⠻⡄⣀⣤⣴⡾⠖⠚⠿⡀   ⠈⣧⠁⠹⠆  ⣇     "
 $e $u"  ⢀⢸⣀⣼⣿⣼⡆ ⢀⡘⡇  ⠹⡟⢷⡜⢉⣠⣠⣠⣀⣤⡿⣛⣥⣶⣾⡿⠛⠿⠿⣶⣦⡤⢹ ⢀   ⢹⡄    "
 $e $u"  ⢸⢸⡛⠁ ⠙⢿⠋⠉⠉⠻   ⢿⣄⠈⠁   ⢉⢟⣴⡿⠿$b⠟⢁⠇ $u   ⠹⣿⠻⡇⢸   ⠈⣷   " 
 $e $u"⣀⣀⣘⣿⡇ ⢀⣠⣤⣶⣶⣶⣾⣦⡀ ⠈⡿      ⣿$b⠟⠳⠦⡤⠊    $u ⣸⠇ ⡇⣼ ⢰  ⢹⣇ "  
 $e $u"⠛⠁⠈⣿⣷⣧⣴⣿⠿⠛⣿⠿⣿⣿⡿⠗         ⠁  ⣠⣴⣶⠿⠿⠿⡷⢛⠕⠷⡄⣧⣿ ⢸  ⠸⣿⡄  "
 $e $u" ⢠⣿⢿⣿⣿⠁ $b ⠈⠳⠤⠶⠃ $u ⢰⡀       ⣠⣿⣿⠟⣱⠒⡠⢆⡴⣣⣯⢞⣴⡟⢿⡄⡏   ⡏⢷⡀ "
 $e $u" ⡌⣿ ⠙⣿⡦⢀⣤⡴⣶⠖⣲⠆⢀⠞⠁⠱     ⠠⣾⠟⠛⡡⠞⠁⢀⡴⢋⢎⣽⡿⣫⠋ ⠘⢷⠃⡄  ⡇⠈⣿⡀   "
 $e $u" ⣇⢹⣦ ⠼⢃⡾⢋⣶⢃⡼⣹⡳⠃⠊        ⠁   ⠈⠠⠋ ⡰⠋ ⢘⣇⡇ ⢠⠟ ⡇    ⢹⡵  "
 $e $u" ⢻⣌⢿⡆ ⡝⣼⠟⣩⢏⣾⠟⠁                ⢀⠞    ⠈ ⣠⠏⣠⣾⡇    ⠘⣷  "
 $e $u" ⢸⣿⣿⣷⠆⢠⠏⡴⠃⡡⠋      ⣀⣠⠤⠔⠒⠤⣄⣀  ⢀⣰⠏    ⢀⣠⡾⠗⠋⢰⠏⡇  ⠘ ⠰⢻   "
 $e $u"⣇ ⠘⣿⣿⣟⠻⣄⡞ ⠐⠁     ⣠⠞⣩⣤⣶⣶⣾⣷⣶⣬⣿⣿⣿⡏    ⠉⠉⠁   ⢸⡆⡇         "
 $e $u"⠹⡄ ⠹⣿⣿⡄ ⠉⠉ ⡀  ⠈⢻⣾⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿           ⣼⣇⣧        "
 $e $u"⣿⢦⣀⠘⢿⣷⡀  ⡀⢦    ⠹⣿⣿⠏⠙⢻⣿⡿⠛⠉ ⠸⣿⠃         ⢀⣴⣿⣿⣿  ⡆  ⡀         "
 $e $u"⢼⣿ ⠈⢳⣤⣉⣻⣤⣀⣉⣩⠆    ⠹⡿  ⠈⡿    ⣸⡇      ⠓⠂ ⣠⣾⣿⣿⡿⢿⡄ ⣧  ⠹    "
 $e $u"⣾⠃ ⣠⣿⣿⣿⣿⣿⣿⣄       ⡇  ⢸⡇  ⢠⠴⣿⡄       ⣠⣾⣿⣿⣿⡿⣧⣀⠧⣰⣻⢄       "
 $e $u"⠛⠶⢾⣿⣽⣭⣽⣭⢹⣷ ⢹⣦⣀    ⡄  ⣸⡀  ⠁⣰⣧⣽    ⢀⣴⣾⣿⣿⡟⣻⣿⣿⣿⣿⢠⣿⣧⡸⣷⣄      "
 $e $u"  ⠈⠙⠿⣿⣿⣿⠏ ⣾⣿⣿⣷⣦⣀ ⢇  ⠈⠁ ⣠⠔⠁    ⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠏⣼⣿⠏⣷⡈⠉        "
 $e $u"      ⠙⠻⣶⣾⣿⣿⣿⣿⣿⣿⣷⣾⡆   ⡾⠁   ⣀⡴⠞⠛⣛⣿⡿⠿⠛⠛⠉⠉   ⢰⣿⡿⠂⠈⠻⡄     "
 $e $u"         ⠙⢎⠉⠛⠻⠿⠿⠿⠿⠿⣇⠠⠸⣇⣀⣤⣴⣾⡭⠶⠛⠋⠉          ⣾⣿⠇   ⠘      "
 $e $u"           ⠑⣤⡀     ⠈⣳ ⣿⠛⠻⠛⠉              ⣸⣿⡯       "
 
echo -e "$u╔═════════════════════════════════╗$u"
echo -e "$u║     SELAMAT DATANG SAYANG       ║$u"
echo -e "$u║                                 ║$u"
echo -e "$u╚═════════════════════════════════╝$u"
echo -e "$u║ $k[01]$h. MENU OS                   $u║"
echo -e "$u║ $k[02]$h. MENU SPAM PAIR WA         $u║"
echo -e "$u║ $k[03]$h. MENU PHIS FOR CAM         $u║"
echo -e "$u║ $k[04]$h. MENU WATERMAX             $u║"
echo -e "$u║ $k[05]$h. MENU SPAM GMAIL           $u║"
echo -e "$u║ $k[06]$h. MENU DDOS                 $u║"
echo -e "$u║ $k[07]$h. MENU OSINT                $u║"
echo -e "$u║ $k[08]$h. MENU BOT WA               $u║"
echo -e "$u║ $k[09]$h. MENU SEKEER               $u║"
echo -e "$u║ $k[10]$h. MENU TELEGRAM HACKING     $u║"
echo -e "$u╚════════════════════════════════╝$u"
echo -e "$u║"
echo -e "$u║"
echo -e "$u║"
read -p "╚═════(CY78㉿ROOT)═════>: " cy78
mpv /MUSIK.mp3
if [ "$cy78" = 1 ] || [ "$cy78" = 01 ]; then
    clear
    termux-setup-storage -y
    clear
$e $u"   ⣀⢀⣠⣤⠴⠶⠚⠛⠉⣹⡇ ⢸     ⢰⣄    ⠈⢦⢰     ⠈⢳⡀⠈⢧    ⢸    "
 $e $u" ⠉   ⡏ ⢰⠃   ⣿⡇ ⢸⡀    ⢸⣸⡆   ⠰⣌⣧⡆ ⢷⡀  ⣄⢳  ⢣   ⢸    "
 $e $u"     ⡇ ⠘   ⢀⣿⣇ ⠸⡇⣆    ⣿⣿⡀   ⢹⣾⡇ ⢸⢣  ⠘⣿⣇ ⠈⢧  ⠘ ⢠   "
 $e $u"    ⢀⡇ ⡀   ⢸⠈⢻⡄ ⢷⣿    ⢹⡏⣇ ⣀⣀ ⣿⣧ ⢸⠾⣇⣠⣄⣸⣿⡄ ⠘⡆    ⠆    "
 $e $u"    ⣾⢿ ⠇   ⢸  ⢳⡀⢸⣿⡆   ⣬⣿⡿⠟⠋⠉⠙⠻⣽⣀⡏ ⠙⠃⢹⡙⡿⣷  ⢹    ⠰⠒ "
 $e $u"   ⢸⣿⣿⣇⢸   ⢸⣦⣤⡀⣷⣸⡟⢧⣀⡴⠶⠿⠻⡄⣀⣤⣴⡾⠖⠚⠿⡀   ⠈⣧⠁⠹⠆  ⣇     "
 $e $u"  ⢀⢸⣀⣼⣿⣼⡆ ⢀⡘⡇  ⠹⡟⢷⡜⢉⣠⣠⣠⣀⣤⡿⣛⣥⣶⣾⡿⠛⠿⠿⣶⣦⡤⢹ ⢀   ⢹⡄    "
 $e $u"  ⢸⢸⡛⠁ ⠙⢿⠋⠉⠉⠻   ⢿⣄⠈⠁   ⢉⢟⣴⡿⠿$b⠟⢁⠇ $u   ⠹⣿⠻⡇⢸   ⠈⣷   "
 $e $u"⣀⣀⣘⣿⡇ ⢀⣠⣤⣶⣶⣶⣾⣦⡀ ⠈⡿      ⣿$b⠟⠳⠦⡤⠊    $u ⣸⠇ ⡇⣼ ⢰  ⢹⣇ "
 $e $u"⠛⠁⠈⣿⣷⣧⣴⣿⠿⠛⣿⠿⣿⣿⡿⠗         ⠁  ⣠⣴⣶⠿⠿⠿⡷⢛⠕⠷⡄⣧⣿ ⢸  ⠸⣿⡄  "
 $e $u" ⢠⣿⢿⣿⣿⠁ $b ⠈⠳⠤⠶⠃ $u ⢰⡀       ⣠⣿⣿⠟⣱⠒⡠⢆⡴⣣⣯⢞⣴⡟⢿⡄⡏   ⡏⢷⡀ "
 $e $u" ⡌⣿ ⠙⣿⡦⢀⣤⡴⣶⠖⣲⠆⢀⠞⠁⠱     ⠠⣾⠟⠛⡡⠞⠁⢀⡴⢋⢎⣽⡿⣫⠋ ⠘⢷⠃⡄  ⡇⠈⣿⡀   "
 $e $u" ⣇⢹⣦ ⠼⢃⡾⢋⣶⢃⡼⣹⡳⠃⠊        ⠁   ⠈⠠⠋ ⡰⠋ ⢘⣇⡇ ⢠⠟ ⡇    ⢹⡵  "
 $e $u" ⢻⣌⢿⡆ ⡝⣼⠟⣩⢏⣾⠟⠁                ⢀⠞    ⠈ ⣠⠏⣠⣾⡇    ⠘⣷  "
 $e $u" ⢸⣿⣿⣷⠆⢠⠏⡴⠃⡡⠋      ⣀⣠⠤⠔⠒⠤⣄⣀  ⢀⣰⠏    ⢀⣠⡾⠗⠋⢰⠏⡇  ⠘ ⠰⢻   "
 $e $u"⣇ ⠘⣿⣿⣟⠻⣄⡞ ⠐⠁     ⣠⠞⣩⣤⣶⣶⣾⣷⣶⣬⣿⣿⣿⡏    ⠉⠉⠁   ⢸⡆⡇         "
 $e $u"⠹⡄ ⠹⣿⣿⡄ ⠉⠉ ⡀  ⠈⢻⣾⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿           ⣼⣇⣧        "
 $e $u"⣿⢦⣀⠘⢿⣷⡀  ⡀⢦    ⠹⣿⣿⠏⠙⢻⣿⡿⠛⠉ ⠸⣿⠃         ⢀⣴⣿⣿⣿  ⡆  ⡀         "
 $e $u"⢼⣿ ⠈⢳⣤⣉⣻⣤⣀⣉⣩⠆    ⠹⡿  ⠈⡿    ⣸⡇      ⠓⠂ ⣠⣾⣿⣿⡿⢿⡄ ⣧  ⠹    "
 $e $u"⣾⠃ ⣠⣿⣿⣿⣿⣿⣿⣄       ⡇  ⢸⡇  ⢠⠴⣿⡄       ⣠⣾⣿⣿⣿⡿⣧⣀⠧⣰⣻⢄       "
 $e $u"⠛⠶⢾⣿⣽⣭⣽⣭⢹⣷ ⢹⣦⣀    ⡄  ⣸⡀  ⠁⣰⣧⣽    ⢀⣴⣾⣿⣿⡟⣻⣿⣿⣿⣿⢠⣿⣧⡸⣷⣄      "
 $e $u"  ⠈⠙⠿⣿⣿⣿⠏ ⣾⣿⣿⣷⣦⣀ ⢇  ⠈⠁ ⣠⠔⠁    ⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠏⣼⣿⠏⣷⡈⠉        "
 $e $u"      ⠙⠻⣶⣾⣿⣿⣿⣿⣿⣿⣷⣾⡆   ⡾⠁   ⣀⡴⠞⠛⣛⣿⡿⠿⠛⠛⠉⠉   ⢰⣿⡿⠂⠈⠻⡄     "
 $e $u"         ⠙⢎⠉⠛⠻⠿⠿⠿⠿⠿⣇⠠⠸⣇⣀⣤⣴⣾⡭⠶⠛⠋⠉          ⣾⣿⠇   ⠘      "
 $e $u"           ⠑⣤⡀     ⠈⣳ ⣿⠛⠻⠛⠉              ⣸⣿⡯       "    
    echo -e "$b SAYANG KU INI LINK COPY SALIN DI CHROME DOWNLOAND  https://drive.google.com/file/d/13Dyvq71yU4tyBYBMi4Pba4sbzwTL7uuy/view?usp=drivesdk"
   echo -e ""
    echo -e "$b SAYANG KU INI LINK COPY SALIN DI CHROME DOWNLOAND  https://drive.google.com/file/d/1-1DsPqZNsNDsLBLy30R6pmDloISyBMvE/view?usp=drivesdk"
    echo -e ""
    echo -e "$b SAYANG KU INI LINK COPY SALIN DI CHROME DOWNLOAND  https://drive.google.com/file/d/1-enmrbDmdwIARvY2MMdYWSCSjZ7eo7ba/view?usp=drivesdk"
    echo -e ""
    echo -e "$b SAYANG KU INI LINK COPY SALIN DI CHROME DOWNLOAND https://drive.google.com/file/d/1-2SiTBcZpem2DshNTlMTlq18SdY-0FSZ/view?usp=drivesdk"
    echo -e ""
    echo -e "$b Selesai! INSTALL LANGSUNG KE SAYANG YA"
    fi

if [ "$cy78" = 2 ] || [ "$cy78" = 02 ]; then
    clear
    echo -e "$h MENU SPAM PAIR WA."
    raed -p "ENTER 2 KALI"   

    fi

if [ "$cy78" = 3 ] || [ "$cy78" = 03 ]; then
    
if [ "$cy78" = 1 ] || [ "$cy78" = 01 ]; 
then
 mpv /MUSIK.mp3
fi
if [ "$cy78" = 4 ] || [ "$cy78" = 04 ]; then
    clear
    echo -e "$h MENU WATERMAX BELUM TERSEDIA."
   clear
git clone https://github.com/HUNTERKINGCY78/KALI
cd KALI
bash 1
fi

if [ "$cy78" = 8 ] || [ "$cy78" = 08 ]; then
    clear
  termux-setup-storage -y
    clear
exit
mpv /keluar.mp3
$e $u "SELAMAT MENCOBA YA SAYANG "
fi

if [ "$cy78" = 5 ] || [ "$cy78" = 05 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear

fi


if [ "$cy78" = 6 ] || [ "$cy78" = 06 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear

fi


if [ "$cy78" = 7 ] || [ "$cy78" = 07 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear

fi


if [ "$cy78" = 8 ] || [ "$cy78" = 08 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear


fi



if [ "$cy78" = 9 ] || [ "$cy78" = 09 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear


fi


if [ "$cy78" = 10 ] || [ "$cy78" = 10 ]; then
mpv /MUSIK.mp3
clear
termux-setup-storage -y
clear

fi
